package SecuritySystem;


/**
* SecuritySystem/Alarm.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Wednesday, 19 April 2017 20:44:28 o'clock BST
*/

public final class Alarm implements org.omg.CORBA.portable.IDLEntity
{
  public int time = (int)0;
  public int date = (int)0;
  public String room = null;

  public Alarm ()
  {
  } // ctor

  public Alarm (int _time, int _date, String _room)
  {
    time = _time;
    date = _date;
    room = _room;
  } // ctor

} // class Alarm
