package SecuritySystem;


/**
* SecuritySystem/AlarmLogHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Wednesday, 19 April 2017 20:44:28 o'clock BST
*/

abstract public class AlarmLogHelper
{
  private static String  _id = "IDL:SecuritySystem/AlarmLog:1.0";

  public static void insert (org.omg.CORBA.Any a, SecuritySystem.Alarm[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SecuritySystem.Alarm[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = SecuritySystem.AlarmHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (SecuritySystem.AlarmLogHelper.id (), "AlarmLog", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SecuritySystem.Alarm[] read (org.omg.CORBA.portable.InputStream istream)
  {
    SecuritySystem.Alarm value[] = null;
    int _len0 = istream.read_long ();
    value = new SecuritySystem.Alarm[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = SecuritySystem.AlarmHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SecuritySystem.Alarm[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      SecuritySystem.AlarmHelper.write (ostream, value[_i0]);
  }

}
