package SecuritySystem;


/**
* SecuritySystem/Alert.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Tuesday, 23 May 2017 16:59:47 o'clock BST
*/

public final class Alert implements org.omg.CORBA.portable.IDLEntity
{
  public int time = (int)0;
  public int date = (int)0;
  public String name = null;
  public String room = null;

  public Alert ()
  {
  } // ctor

  public Alert (int _time, int _date, String _name, String _room)
  {
    time = _time;
    date = _date;
    name = _name;
    room = _room;
  } // ctor

} // class Alert
