package SecuritySystem;

/**
* SecuritySystem/AlertHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Tuesday, 23 May 2017 16:59:47 o'clock BST
*/

public final class AlertHolder implements org.omg.CORBA.portable.Streamable
{
  public SecuritySystem.Alert value = null;

  public AlertHolder ()
  {
  }

  public AlertHolder (SecuritySystem.Alert initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SecuritySystem.AlertHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SecuritySystem.AlertHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SecuritySystem.AlertHelper.type ();
  }

}
