package SecuritySystem;


/**
* SecuritySystem/CameraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Tuesday, 23 May 2017 17:43:20 o'clock BST
*/

public interface CameraOperations 
{
} // interface CameraOperations
