package SecuritySystem;

/**
* SecuritySystem/CameraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Tuesday, 23 May 2017 17:43:19 o'clock BST
*/

public final class CameraHolder implements org.omg.CORBA.portable.Streamable
{
  public SecuritySystem.Camera value = null;

  public CameraHolder ()
  {
  }

  public CameraHolder (SecuritySystem.Camera initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SecuritySystem.CameraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SecuritySystem.CameraHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SecuritySystem.CameraHelper.type ();
  }

}
