package SecuritySystem;


/**
* SecuritySystem/DevicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Wednesday, 19 April 2017 20:44:28 o'clock BST
*/

public abstract class DevicePOA extends org.omg.PortableServer.Servant
 implements SecuritySystem.DeviceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_name", new java.lang.Integer (0));
    _methods.put ("_set_name", new java.lang.Integer (1));
    _methods.put ("_get_room", new java.lang.Integer (2));
    _methods.put ("_set_room", new java.lang.Integer (3));
    _methods.put ("_get_status", new java.lang.Integer (4));
    _methods.put ("_set_status", new java.lang.Integer (5));
    _methods.put ("_get_onOff", new java.lang.Integer (6));
    _methods.put ("_set_onOff", new java.lang.Integer (7));
    _methods.put ("_get_currentImage", new java.lang.Integer (8));
    _methods.put ("_set_currentImage", new java.lang.Integer (9));
    _methods.put ("trigger", new java.lang.Integer (10));
    _methods.put ("toggleOn", new java.lang.Integer (11));
    _methods.put ("reset", new java.lang.Integer (12));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SecuritySystem/Device/_get_name
       {
         String $result = null;
         $result = this.name ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // SecuritySystem/Device/_set_name
       {
         String newName = in.read_string ();
         this.name (newName);
         out = $rh.createReply();
         break;
       }

       case 2:  // SecuritySystem/Device/_get_room
       {
         String $result = null;
         $result = this.room ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // SecuritySystem/Device/_set_room
       {
         String newRoom = in.read_string ();
         this.room (newRoom);
         out = $rh.createReply();
         break;
       }

       case 4:  // SecuritySystem/Device/_get_status
       {
         boolean $result = false;
         $result = this.status ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // SecuritySystem/Device/_set_status
       {
         boolean newStatus = in.read_boolean ();
         this.status (newStatus);
         out = $rh.createReply();
         break;
       }

       case 6:  // SecuritySystem/Device/_get_onOff
       {
         boolean $result = false;
         $result = this.onOff ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // SecuritySystem/Device/_set_onOff
       {
         boolean newOnOff = in.read_boolean ();
         this.onOff (newOnOff);
         out = $rh.createReply();
         break;
       }

       case 8:  // SecuritySystem/Device/_get_currentImage
       {
         SecuritySystem.Image $result = null;
         $result = this.currentImage ();
         out = $rh.createReply();
         SecuritySystem.ImageHelper.write (out, $result);
         break;
       }

       case 9:  // SecuritySystem/Device/_set_currentImage
       {
         SecuritySystem.Image newCurrentImage = SecuritySystem.ImageHelper.read (in);
         this.currentImage (newCurrentImage);
         out = $rh.createReply();
         break;
       }

       case 10:  // SecuritySystem/Device/trigger
       {
         this.trigger ();
         out = $rh.createReply();
         break;
       }

       case 11:  // SecuritySystem/Device/toggleOn
       {
         this.toggleOn ();
         out = $rh.createReply();
         break;
       }

       case 12:  // SecuritySystem/Device/reset
       {
         this.reset ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SecuritySystem/Device:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Device _this() 
  {
    return DeviceHelper.narrow(
    super._this_object());
  }

  public Device _this(org.omg.CORBA.ORB orb) 
  {
    return DeviceHelper.narrow(
    super._this_object(orb));
  }


} // class DevicePOA
