package SecuritySystem;

/**
* SecuritySystem/DeviceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Wednesday, 19 April 2017 20:44:28 o'clock BST
*/

public final class DeviceHolder implements org.omg.CORBA.portable.Streamable
{
  public SecuritySystem.Device value = null;

  public DeviceHolder ()
  {
  }

  public DeviceHolder (SecuritySystem.Device initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SecuritySystem.DeviceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SecuritySystem.DeviceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SecuritySystem.DeviceHelper.type ();
  }

}
