package SecuritySystem;

/**
* SecuritySystem/HubHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Tuesday, 23 May 2017 17:43:20 o'clock BST
*/

public final class HubHolder implements org.omg.CORBA.portable.Streamable
{
  public SecuritySystem.Hub value = null;

  public HubHolder ()
  {
  }

  public HubHolder (SecuritySystem.Hub initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SecuritySystem.HubHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SecuritySystem.HubHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SecuritySystem.HubHelper.type ();
  }

}
