package SecuritySystem;


/**
* SecuritySystem/HubOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Tuesday, 23 May 2017 17:43:20 o'clock BST
*/

public interface HubOperations 
{
  void sensorAlert (String name, String room);
  void sensorOnOff (String name, String room, boolean onOff);
  void cameraAlert (String name, String room);
  void sensorReset (String name, String room);
  void logAlarm (String log);
} // interface HubOperations
