package SecuritySystem;


/**
* SecuritySystem/Image.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Tuesday, 23 May 2017 16:59:47 o'clock BST
*/

public final class Image implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public int time = (int)0;
  public int date = (int)0;

  public Image ()
  {
  } // ctor

  public Image (String _name, int _time, int _date)
  {
    name = _name;
    time = _time;
    date = _date;
  } // ctor

} // class Image
