package SecuritySystem;

/**
* SecuritySystem/ImageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Tuesday, 23 May 2017 16:59:47 o'clock BST
*/

public final class ImageHolder implements org.omg.CORBA.portable.Streamable
{
  public SecuritySystem.Image value = null;

  public ImageHolder ()
  {
  }

  public ImageHolder (SecuritySystem.Image initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SecuritySystem.ImageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SecuritySystem.ImageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SecuritySystem.ImageHelper.type ();
  }

}
