package SecuritySystem;

/**
* SecuritySystem/OfficeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Tuesday, 23 May 2017 17:43:20 o'clock BST
*/

public final class OfficeHolder implements org.omg.CORBA.portable.Streamable
{
  public SecuritySystem.Office value = null;

  public OfficeHolder ()
  {
  }

  public OfficeHolder (SecuritySystem.Office initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SecuritySystem.OfficeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SecuritySystem.OfficeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SecuritySystem.OfficeHelper.type ();
  }

}
