package SecuritySystem;


/**
* SecuritySystem/OfficeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Tuesday, 23 May 2017 17:43:20 o'clock BST
*/

abstract public class OfficeHelper
{
  private static String  _id = "IDL:SecuritySystem/Office:1.0";

  public static void insert (org.omg.CORBA.Any a, SecuritySystem.Office that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SecuritySystem.Office extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SecuritySystem.OfficeHelper.id (), "Office");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SecuritySystem.Office read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OfficeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SecuritySystem.Office value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SecuritySystem.Office narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SecuritySystem.Office)
      return (SecuritySystem.Office)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SecuritySystem._OfficeStub stub = new SecuritySystem._OfficeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SecuritySystem.Office unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SecuritySystem.Office)
      return (SecuritySystem.Office)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SecuritySystem._OfficeStub stub = new SecuritySystem._OfficeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
