package SecuritySystem;


/**
* SecuritySystem/RoomCoverageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Wednesday, 19 April 2017 20:44:28 o'clock BST
*/

public final class RoomCoverageHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public RoomCoverageHolder ()
  {
  }

  public RoomCoverageHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SecuritySystem.RoomCoverageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SecuritySystem.RoomCoverageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SecuritySystem.RoomCoverageHelper.type ();
  }

}
