package SecuritySystem;

/**
* SecuritySystem/SensorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SecuritySystem.idl
* Tuesday, 23 May 2017 17:43:20 o'clock BST
*/

public final class SensorHolder implements org.omg.CORBA.portable.Streamable
{
  public SecuritySystem.Sensor value = null;

  public SensorHolder ()
  {
  }

  public SensorHolder (SecuritySystem.Sensor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SecuritySystem.SensorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SecuritySystem.SensorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SecuritySystem.SensorHelper.type ();
  }

}
